### ISSUE TITLE
Laravel Collections

### ISSUE THREAD

**Issue by tzs007** [luqmanrom/firebase-php#2]
Can I convert to a Laravel collection what I get from Firebase?

**Comment by luqmanrom** [comment]
I am trying to make it as generic as possible, not focusing on a specific framework. So for now, it will return array. But if you need to convert it to collection, you can use `collect` helper functions in Laravel.

**Comment by tzs007** [comment]
Yep, I'm done with it.

$firebase->setPath('todos/');
$tasks = $firebase->get('');
$collection = collect(json_decode($tasks));

Everything fine in Laravel with this package.
